const state={day:1,money:120,rep:4,orders:0,served:0,stock:{meatRoll:0,herb:0,shrimp:0,rice:0,meatStack:0,bun:0},servedNames:[],open:false};
const ingredients=[{id:'meatRoll',name:'Thịt cuốn',desc:'Thịt thái mỏng, mềm thơm',image:'/assets/01_thit_cuon.png',unit:'phần',cost:16},{id:'herb',name:'Rau xanh',desc:'Xà lách, húng tươi',image:'/assets/02_rau.png',unit:'phần',cost:10},{id:'shrimp',name:'Tôm tươi',desc:'Ngọt thịt, size vừa',image:'/assets/03_tom.png',unit:'phần',cost:18},{id:'rice',name:'Bánh tráng',desc:'Mềm dai, không rách',image:'/assets/04_banh_trang.png',unit:'xấp',cost:12},{id:'meatStack',name:'Thịt xếp',desc:'Thịt xếp lớp đậm vị',image:'/assets/05_thit_xep.png',unit:'phần',cost:18},{id:'bun',name:'Bún tươi',desc:'Sợi bún mềm vừa',image:'/assets/06_bun.png',unit:'phần',cost:8}];
const menu=[{name:'Gỏi cuốn tôm thịt',desc:'Tôm · thịt · rau · bún',emoji:'🍤',price:28,need:['rice','meatRoll','herb']},{name:'Cuốn chay xanh',desc:'Nấm · đậu hũ · rau xanh',emoji:'🥬',price:24,need:['rice','meatRoll','herb']},{name:'Combo 3 cuốn',desc:'Mix vị + sốt đặc biệt',emoji:'🥢',price:42,need:['rice','meatRoll','meatStack','herb']}];
const upgrades=[{name:'Bàn cuốn rộng hơn',desc:'Thêm 2 khách mỗi ngày',emoji:'🪑',cost:75,bonus:2},{name:'Hộp giữ rau tươi',desc:'Giảm hao hụt nguyên liệu',emoji:'🧊',cost:95,bonus:1},{name:'Bảng hiệu đèn lồng',desc:'Tăng danh tiếng mỗi đơn',emoji:'🏮',cost:130,bonus:0}];
function money(n){return `${n}k`}; function el(id){return document.getElementById(id)}
function render(){el('day').textContent=state.day;el('footerDay').textContent=String(state.day).padStart(2,'0');el('money').textContent=money(state.money);el('rep').textContent='★'.repeat(state.rep)+'☆'.repeat(5-state.rep);el('orders').textContent=`${state.served} / 8`;el('phase').textContent=state.open?'Đang bán':'Chuẩn bị';
 el('ingredients').innerHTML=ingredients.map(x=>`<article class="ingredient"><span class="emoji ingredient-image"><img src="${x.image}" alt="${x.name}" loading="lazy"></span><div><h4>${x.name}</h4><p>${x.desc} · ${money(x.cost)}/${x.unit}</p><div class="stepper"><button data-minus="${x.id}" ${state.open?'disabled':''}>−</button><span>${state.stock[x.id]}</span><button data-plus="${x.id}" ${state.open?'disabled':''}>+</button></div></div><span class="stock-num">${state.stock[x.id]}<small> ${x.unit}</small></span></article>`).join('');
 el('upgrades').innerHTML=upgrades.map((x,i)=>`<article class="upgrade"><span class="emoji ingredient-image"><img src="${x.image}" alt="${x.name}" loading="lazy"></span><div><h4>${x.name}</h4><p>${x.desc}</p><button data-upgrade="${i}" ${state.money<x.cost?'disabled':''}>Mua · ${money(x.cost)}</button></div></article>`).join('');
 el('menuCards').innerHTML=menu.map(x=>`<article class="menu-card"><span class="emoji ingredient-image"><img src="${x.image}" alt="${x.name}" loading="lazy"></span><div><h4>${x.name}</h4><p>${x.desc}</p><strong>${money(x.price)}</strong></div></article>`).join('');
 el('summaryBody').innerHTML=`<div class="summary-number">${money(state.money)}</div><p class="muted">Số dư cuối ngày hiện tại</p><div class="summary-row"><span>Đơn đã phục vụ</span><span>${state.served} đơn</span></div><div class="summary-row"><span>Khách hài lòng</span><span>${state.rep}/5 sao</span></div><div class="summary-row"><span>Trạng thái quầy</span><span>${state.open?'Đang mở cửa':'Đang nghỉ'}</span></div>`;
 if(!state.open){el('ordersList').innerHTML='<div class="empty-state">🥢<br><strong>Chưa có khách nào</strong><small>Bấm “Mở quầy bán hàng” để bắt đầu</small></div>';el('stageTitle').textContent='Quầy đang nghỉ';el('stageSub').textContent='Chuẩn bị xong thì mở cửa đón khách nhé'}
 el('openShop').disabled=state.open||state.stock.rice<1||state.stock.herb<1;el('prepText').textContent=state.open?'Quầy đang mở cửa!':'Sẵn sàng vào bếp?';el('prepSub').textContent=state.open?'Khách đang chờ món nóng hổi.':'Nhập ít nhất bánh tráng và rau để mở quầy.';
}
function toast(s){const t=el('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function showOrders(){const pool=[{n:'Bé Na',c:'🧒',want:0},{n:'Chú Tư',c:'👨‍🌾',want:2},{n:'Cô Mai',c:'👩‍🍳',want:1},{n:'Anh shipper',c:'🧑‍🦱',want:0}];el('ordersList').innerHTML=pool.map((x,i)=>`<article class="order"><span class="badge">${i%2?'Ít cay':'Đói bụng'}</span><span class="customer">${x.c}</span><h4>${x.n}</h4><p>${menu[x.want].name}</p><button data-serve="${i}">Cuốn cho khách · ${money(menu[x.want].price)}</button></article>`).join('');el('stageTitle').textContent='Khách đang ghé quầy';el('stageSub').textContent='Cuốn nhanh tay để khách không phải chờ lâu';}
document.addEventListener('click',e=>{const plus=e.target.dataset.plus,minus=e.target.dataset.minus;if(plus||minus){const id=plus||minus;const item=ingredients.find(x=>x.id===id);if(plus&&state.money>=item.cost){state.money-=item.cost;state.stock[id]++;toast(`Đã nhập ${item.name}`)}else if(minus&&state.stock[id]>0){state.stock[id]--;state.money+=item.cost;toast('Đã trả lại một phần hàng')}render()}if(e.target.dataset.upgrade){const x=upgrades[e.target.dataset.upgrade];if(state.money>=x.cost){state.money-=x.cost;toast(`Đã nâng cấp: ${x.name}`);render()}}if(e.target.dataset.serve){const card=e.target.closest('.order');const want=Number(e.target.dataset.serve)%2?2:0;const recipe=menu[want];if(recipe.need.every(k=>state.stock[k]>0)){recipe.need.forEach(k=>state.stock[k]--);state.money+=recipe.price;state.served++;state.rep=Math.min(5,state.rep+(state.served%3===0?1:0));card.remove();toast('Khách nhận cuốn, cười tươi rói 🫶');if(!el('ordersList').children.length){el('stageTitle').textContent='Quầy vắng khách';el('stageSub').textContent='Một ngày bán hàng thật vui!'}}else toast('Thiếu nguyên liệu, nhập thêm nhé!');render()}});
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active-panel'));btn.classList.add('active');el(btn.dataset.tab).classList.add('active-panel')});
el('openShop').onclick=()=>{if(state.stock.rice&&state.stock.herb){state.open=true;showOrders();render();toast('Mở quầy rồi, khách tới kìa!')}};el('resetBtn').onclick=()=>{Object.assign(state,{day:1,money:120,rep:4,orders:0,served:0,stock:{meatRoll:0,herb:0,shrimp:0,rice:0,meatStack:0,bun:0},open:false});render();toast('Đã bắt đầu lại ngày đầu tiên')};render();




